### PR TITLE
blog: Add HiKey970 Mainlining Update - Part 2 blog

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
Add HiKey970 Mainlining Update - Part 2 blog

Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

### CODE REVIEW

**Comment by Mani-Sadhasivam** [comment]
@kylekirkby Thanks for the review. I have added the frontmatter to this blog as well as the previous one.

**Comment by kylekirkby** [comment]
> @kylekirkby Thanks for the review. I have added the frontmatter to this blog as well as the previous one.

Thanks @Mani-Sadhasivam !

**Comment by Mani-Sadhasivam** [comment]
@kylekirkby Sure. So no need to pass thumbnails anymore?

**Comment by kylekirkby** [comment]
> @kylekirkby Sure. So no need to pass thumbnails anymore?

No not necessary anymore! :) Working on docs

**Pull request merged**
