### PR TITLE
board: cev2: Add the two new CEv2 Boards tb-96ai-3586ce and tb-96aiot…

### PR DESCRIPTION
**Pull request by ric96**
…-1126ce

Signed-off-by: Sahaj Sarup <sahaj.sarup@linaro.org>

### CODE REVIEW

**Comment by kylekirkby** [comment]
@philip-linaro - could you take a look at the 96Boards build? The Jekyll build is complaining that it couldn't find `images/tb-96aiot-1126ce-front.png` but it exists in this pull request. I'm wondering whether there is an issue happening with the merging of sources...

**Comment by ric96** [comment]
@kylekirkby its a folder name typo on my end, pushing a fix

**Comment by ric96** [comment]
Failed links depend on: https://github.com/96boards/documentation/pull/938

**Comment by ric96** [comment]
@kylekirkby

**Review by kylekirkby — APPROVED** [review]

**Pull request merged**
