### PR TITLE
Removed Slack from Support tab

### PR DESCRIPTION
**Pull request by sgermanserrano**
Signed-off-by: sgermanserrano <servando.german.serrano@linaro.org>

### CODE REVIEW

**Comment by kylekirkby** [comment]
@sgermanserrano - Is slack no longer a supported channel for communication?

**Comment by sgermanserrano** [comment]
I don't think so. @sdrobertw please comment

**Comment by kylekirkby** [comment]
> I don't think so. @sdrobertw please comment

Someone has added a question to the slack but haven't had a reply yet? If we are closing the slack account we should at least tell users where to go with a notice or something similar? :)

**Comment by ric96** [comment]
It's not supported anymore, we have moved to dicord.

**Comment by sdrobertw** [comment]
@sgermanserrano Slack is no longer supported. We have since moved to Discord.

Real time communication channels are now IRC and Discord.

**Pull request merged**
