### PR TITLE
openhours/posts: Update calendar link and description to episode 88 and added Coursera blog and fixed blog links

### PR DESCRIPTION
**Pull request by sdrobertw**
Signed-off-by: Robert Wolff <robert.wolff@linaro.org>

### CODE REVIEW

**Comment by shovanuk** [comment]
Signed-off-by: Shovan shovan@linaro.org

**Comment by pcolmer** [comment]
What is the intended purpose of the calendar links? It looks like you have to have a Google account before you can access the URL. Is that expected?

**Comment by sdrobertw** [comment]
@pcolmer We are looking for a better way to allow people to add the event to a calendar. It was requested we have a way for people to add the event some way. 

I am totally for removing the link... Honestly, it is not a fun thing to updated each week.

**Comment by sdrobertw** [comment]
This PR is a 3 parter... I Just added some link fixes to test the link checker system. Once @ric96 submits his fixed to the documentation repository, I will dive in to fix the rest of the ones on the report.

**Pull request merged**
