### PR TITLE
add guides tab to documentation page

### PR DESCRIPTION
**Pull request by ric96**
Signed-off-by: Sahaj Sarup <sahaj.sarup@linaro.org>

### CODE REVIEW

**Comment by sdrobertw** [comment]
@ric96 I will approve, but I think this one is better merged by @kylekirkby considering I have never added a new tab before. 

Did he walk you through this process?

**Comment by kylekirkby** [comment]
Are we going to go with guides.md.html ? I think it should be /documentation/guides/

**Comment by ric96** [comment]
@sdrobertw @kylekirkby I'll revise this patch with /documentation/guides/

**Comment by kylekirkby** [comment]
Any updates on this @ric96 ?

**Comment by ric96** [comment]
@kylekirkby updated

**Pull request merged**
