### PR TITLE
README: update the list of supported OS

### PR DESCRIPTION
**Pull request by ndechesne**

### CODE REVIEW

**Comment by sgermanserrano** [comment]
@ndechesne can you target `develop` instead of `master`?

**Comment by ndechesne** [comment]
hmm. I use the 'edit on github' button, and I don't see 'develop'. what is 'develop'?

**Comment by sgermanserrano** [comment]
We are using a `develop` branch to commit changes before they go into `master`. The repo should be using `develop` by default for PRs, can you check if you can change the branch before clicking the 'edit' button?

**Comment by ndechesne** [comment]
ah, ok! I didn't realize that this PR was against the website. Usually I make changes only in documentation.. 
it would be good if you could make the 'edit in github' do the right thing by defaul.

**Pull request merged**
