### PR TITLE
go: Add go page for 96Boards India initiative

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

### CODE REVIEW

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw Please take a look

**Comment by shovanuk** [comment]
Can you also add a link to WhatsApp Group: 
96Boards India WhatsApp Group: http://linaro.co/96boards-whatsapp

**Comment by Mani-Sadhasivam** [comment]
@shovanuk Done!

**Comment by shovanuk** [comment]
Signed-off-by: Shovan shovan@linaro.org

**Pull request merged**
