### PR TITLE
Feature ece191

### PR DESCRIPTION
**Pull request by GaramAn1**
This is first blog of Cryptocurrency register.

### CODE REVIEW

**Comment by sdrobertw** [comment]
@GaramAn1 Extension for blog should be .md (not .dm) could you please update your PR with that change.

**Comment by sdrobertw** [comment]
@GaramAn1 Also, it appears you are using an images called goal.png, but I do not see where you have imported this email. 

Please add this image to the following folder (within website repo) on your fork: 

/assets/images/blog/

and commit to this PR.

**Comment by GaramAn1** [comment]
Thank you for your comments.

I pushed image file. How can I call image file in the blog?

**Comment by sdrobertw** [comment]
@ric96 what do you think?

**Pull request merged**
