### PR TITLE
blog: Add EFY India Electronics Week 2018 summary

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
This adds IEW 2018 summary blog and its relevant images.

Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

### CODE REVIEW

**Comment by sdrobertw** [comment]
@Mani-Sadhasivam please fix broken links found in website repo for merge.

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw Fixed the link but not sure why Jekyll build failed! Seems like all the tests are passed.

**Comment by sdrobertw** [comment]
@kylekirkby is running through some fixes. I will assign Kyle as reviewer for this PR. Once he is done with his fixes, he can merge.

Thanks, @Mani-Sadhasivam

**Comment by Mani-Sadhasivam** [comment]
Guys, can I know how long will it take for you to merge this PR? I have one more blog queued up and it need to go live soon.

**Pull request merged**
