### PR TITLE
openhours: Changes description to episode 93

### PR DESCRIPTION
**Pull request by sdrobertw**
Signed-off-by: Robert Wolff <robert.wolff@linaro.org>

### CODE REVIEW

**Comment by sdrobertw** [comment]
@shovanuk can we merge this even though it is seeing broken links on documentation repo?

**Comment by sdrobertw** [comment]
@shovanuk I have fixed all the links on the website side.

**Comment by shovanuk** [comment]
@sdrobertw looks like there is few more

/documentation/consumer/dragonboard410c/downloads/debian.md.html:
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/dragonboard410c_sdcard_install_debian-*.zip [1]
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/ [1]
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/dragonboard410c_sdcard_developer_debian-*.zip [1]
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/boot-linaro-*-qcom-snapdragon-arm64-*.img.gz [1]
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/linaro-*-alip-qcom-snapdragon-arm64-*.img.gz [1]
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/linaro-*-developer-qcom-snapdragon-arm64-*.img.gz [1]
/documentation/consumer/dragonboard410c/guides/dt-overlays.md.html:
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/ [1]
/documentation/consumer/dragonboard410c/guides/enable-dmic.md.html:
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/ [1]
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/linaro-*-alip-qcom-snapdragon-arm64-*.img.gz [1]
/documentation/consumer/dragonboard410c/guides/enable-spi.md.html:
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/ [1]
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/linaro-*-alip-qcom-snapdragon-arm64-*.img.gz [1]
/documentation/consumer/dragonboard410c/guides/uboot-linux-sd.md.html:
   http://builds.96boards.org/releases/dragonboard410c/linaro/debian/latest/ [1]

**Comment by sdrobertw** [comment]
Thank you @philip-linaro for the feedback: https://github.com/96boards/documentation/pull/296

Considering the nature of this particular PR. I move we merge to facilitate the fixes on documentation repo.

Considering this PR has addressed ALL broken links on website repo, the only way to merge anything in documentation repo will be if this PR is merged.

**Pull request merged**
