### PR TITLE
NovTech added to the /membership/ page

### PR DESCRIPTION
**Pull request by kylekirkby**

### CODE REVIEW

**Comment by kylekirkby** [comment]
@daniel-thompson @ric96 Will anyone be able to help fix these broken snapshots links ?

**Comment by daniel-thompson** [comment]
+@fboudra

@kylekirkby : These have broken because the snapshots were deleted automatically (because they are more than 3 months old).

The ideal fix is to try and get a new build. I think between B&B, SSE and Arm LT there might even be enough momentum now to get it promoted to releases at some point. Anyhow I've pinged @suihkulokki on IRC to see if we can get a new build kicked off (but we can't ping him to this thread since he's not a collaborator for this github project).

**Comment by kylekirkby** [comment]
OK thanks @daniel-thompson!

**Comment by daniel-thompson** [comment]
Riku came through real quick on this! There is now a #18 build so hopefully the link checks will pass now.

**Comment by kylekirkby** [comment]
Thanks @daniel-thompson - running the tests again to verify fix :+1:

**Pull request merged**
