### PR TITLE
link fixes

### PR DESCRIPTION
**Pull request by ric96**
Signed-off-by: Sahaj Sarup <sahaj.sarup@linaro.org>

### CODE REVIEW

**Comment by sdrobertw** [comment]
@kylekirkby I will let him merge.

**Comment by ric96** [comment]
@kylekirkby it's already fixed. its a https://www.96boards.org/ link so it will appear as broken...

**Comment by kylekirkby** [comment]
@ric96 Can we change this to a relative link so we absolutely know for sure all links are fixed before merging ? Otherwise if it's not we may have to another PR with the fix. Then wait for the tests to run and then build the site again. 

Cheers!

**Comment by kylekirkby** [comment]
Once we have got this down to just documentation links we'll merge this and then he documentation fixes.

**Pull request merged**
