### PR TITLE
blog: Add Patient Monitoring System Part 1

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

### CODE REVIEW

**Comment by shovanuk** [comment]
@Mani-Sadhasivam I have updated the content slightly, please review it and send me a new PR

**Comment by Mani-Sadhasivam** [comment]
@shovanuk Can you please add those modifications as comments! Its very hard to figure out the change done by you. thanks

**Comment by shovanuk** [comment]
@Mani-Sadhasivam I copied your content and pasted it on https://www.grammarly.com. It should highlight some of the major issues. Please try it out :)

**Comment by Mani-Sadhasivam** [comment]
@shovanuk Done!

**Pull request merged**
