### PR TITLE
ee: developerbox: Get rid of broken OS link

### PR DESCRIPTION
**Pull request by daniel-thompson**
The OS linked to from here was removed many, many moons ago!

### CODE REVIEW

**Comment by daniel-thompson** [comment]
@kylekirkby @Yang-96Boards @ric96 
Who is responsible reviewing PRs like this one?

**Comment by daniel-thompson** [comment]
> @kylekirkby @Yang-96Boards @ric96
> Who is responsible reviewing PRs like this one?

So, without a reply, I'm going to assume that when the changes relate to document I wrote then I am sufficient on my own ;-)

**Comment by Yang-96Boards** [comment]
It’s sufficient Daniel :-)

Yang

**Comment by daniel-thompson** [comment]
> It’s sufficient Daniel :-)

Sadly it's not... I don't have enough permissions on this repo to review or force-merge my own changes.

To be honest I don't think I have enough permissions in the documentaton repo to force through my own changes either using the GUI (although in that repo I can definitely merge other peoples changes).

**Review by yu-ya0614 — APPROVED** [review]

**Pull request merged**
